language: go
sudo: false
matrix:
  include:
  # "1.x" always refers to the latest Go version, inc. the patch release.
  # e.g. "1.x" is 1.11 until 1.11.1 is available.
  - go: 1.x
    env: LATEST=true
  - go: 1.7.x
  - go: 1.8.x
  - go: 1.9.x
  - go: 1.10.x
  - go: 1.11.x
  - go: tip
  allow_failures:
  - go: tip

before_install:
  # gox simplifies building for multiple architectures
  - go get github.com/mitchellh/gox
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)