[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/jalgoarena/problems-store"

[prune]
  go-tests = true
  unused-packages = true
